import { App, ItemView, Modal, Notice, Plugin, PluginSettingTab, Setting, WorkspaceLeaf, requestUrl } from "obsidian";

const VIEW="sat-nexus-sidebar";
interface Settings { apiUrl:string }
type Q={id:string;questionText:string;questionHtml?:string|null;passage?:string|null;choices?:{key:string;text:string}[]|null;correctAnswer:string;explanation?:string|null;difficulty:string;domain:string;skill:string;subskill?:string|null};
const domains=["Math","Reading & Writing"], skills:{[k:string]:string[]}={Math:["Algebra","Advanced Math","Problem-Solving and Data Analysis","Geometry and Trigonometry"],"Reading & Writing":["Information and Ideas","Craft and Structure","Expression of Ideas","Standard English Conventions"]};
const subs:{[k:string]:string[]}={"Algebra":["Linear equations in one variable","Linear functions","Linear equations in two variables","Systems of two linear equations in two variables","Linear inequalities in one or two variables"],"Advanced Math":["Nonlinear functions","Equivalent expressions"],"Problem-Solving and Data Analysis":["Ratios, rates, proportional relationships, and units","Percentages","One-variable data: distributions and measures of center and spread","Two-variable data: models and scatterplots","Probability and conditional probability"],"Geometry and Trigonometry":["Area and volume","Lines, angles, and triangles","Right triangles and trigonometry","Circles"],"Information and Ideas":["Central Ideas and Details","Command of Evidence","Inferences"],"Craft and Structure":["Words in Context","Text Structure and Purpose","Cross-Text Connections"],"Expression of Ideas":["Rhetorical Synthesis","Transitions"],"Standard English Conventions":["Boundaries","Form, Structure, and Sense"]};
function clean(s:string){return s.replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ")}
function format(q:Q){return `\n> [!question]- SAT Nexus · ${q.domain} · ${q.skill}\n> **${q.difficulty}** · Question ID: ${q.id}\n>\n> ${clean(q.questionText).replace(/\n/g,"\n> ")}\n${q.choices?.map(c=>`> - **${c.key}.** ${clean(c.text)}`).join("\n")??""}\n>\n> <details><summary>Answer and explanation</summary>\n>\n> **Answer:** ${q.correctAnswer}\n>\n> ${clean(q.explanation??"No explanation available.")}\n>\n> </details>\n`}
export default class SatNexus extends Plugin { settings!:Settings; async onload(){this.settings=Object.assign({apiUrl:"https://sat-nexus.vercel.app"},await this.loadData());this.registerView(VIEW,l=>new Sidebar(l,this.app,this.settings));this.addRibbonIcon("book-open","SAT Nexus questions",()=>this.open());this.addCommand({id:"open-sidebar",name:"Open SAT Nexus sidebar",callback:()=>this.open()});this.addCommand({id:"insert-question-id",name:"Insert SAT question by ID",callback:()=>new IdModal(this.app,this.settings,q=>this.insert(q)).open()});this.addSettingTab(new Tab(this.app,this));} async open(){const l=this.app.workspace.getLeavesOfType(VIEW)[0]??this.app.workspace.getRightLeaf(false);if(l){await l.setViewState({type:VIEW,active:true});this.app.workspace.revealLeaf(l)}} insert(q:Q){const e=this.app.workspace.activeEditor?.editor;if(!e){new Notice("Open a note first");return}e.replaceSelection(format(q));new Notice("Question inserted into note")}}
class IdModal extends Modal{constructor(app:App,private s:Settings,private done:(q:Q)=>void){super(app)}onOpen(){this.contentEl.createEl("h2",{text:"Insert SAT question"});const i=this.contentEl.createEl("input",{type:"text",placeholder:"Question ID"});i.addClass("sat-id-input");const b=this.contentEl.createEl("button",{text:"Find question"});b.addEventListener("click",async()=>{try{const r=await requestUrl({url:`${this.s.apiUrl}/api/questions/${encodeURIComponent(i.value.trim())}`});this.done(r.json);this.close()}catch{new Notice("Question ID not found")}});i.focus()}}
class Sidebar extends ItemView{q:Q|null=null;root!:HTMLElement;constructor(l:WorkspaceLeaf,private app:App,private s:Settings){super(l)}getViewType(){return VIEW}getDisplayText(){return "SAT Nexus"}async onOpen(){this.root=this.containerEl;this.root.empty();this.root.addClass("sat-nexus-view");this.render()}async onClose(){} select(label:string,values:string[],on:(v:string)=>void){const s=this.root.createEl("select");s.createEl("option",{text:label,value:""});values.forEach(v=>s.createEl("option",{text:v,value:v}));s.addEventListener("change",()=>on(s.value));return s} render(){this.root.empty();const h=this.root.createDiv("sat-head");h.createEl("div",{text:"SAT NEXUS",cls:"sat-eyebrow"});h.createEl("h2",{text:"Question picker"});h.createEl("p",{text:"Find a question to study or insert into your note."});const id=this.root.createDiv("sat-id-row");const input=id.createEl("input",{type:"text",placeholder:"Enter question ID…"});const go=id.createEl("button",{text:"Insert"});go.onclick=async()=>{try{const r=await requestUrl({url:`${this.s.apiUrl}/api/questions/${encodeURIComponent(input.value.trim())}`});this.q=r.json;this.render()}catch{new Notice("Question ID not found")}};this.root.createEl("div",{text:"FILTER QUESTIONS",cls:"sat-label"});let domain="",skill="",sub="",difficulty="";this.select("Section",domains,v=>{domain=v;this.renderFilter(domain,skill,sub,difficulty)});this.renderFilter(domain,skill,sub,difficulty);if(this.q)this.renderQuestion()}
renderFilter(domain:string,skill:string,sub:string,difficulty:string){const old=this.root.querySelector(".sat-filters");old?.remove();const box=this.root.createDiv("sat-filters");const a=this.selectIn(box,"Category",domain?skills[domain]:[],v=>{skill=v;sub=""});this.selectIn(box,"Subcategory",skill?subs[skill]??[]:[],v=>sub=v);this.selectIn(box,"Difficulty",["Easy","Medium","Hard"],v=>difficulty=v);const b=box.createEl("button",{text:"↻  Random question",cls:"sat-random"});b.onclick=async()=>{const p=new URLSearchParams({random:"1",limit:"1"});if(domain)p.set("domain",domain);if(skill)p.set("skill",skill);if(sub)p.set("subskill",sub);if(difficulty)p.set("difficulty",difficulty);try{const r=await requestUrl({url:`${this.s.apiUrl}/api/questions?${p}`});this.q=r.json.questions?.[0];this.render()}catch{new Notice("Could not load questions")}}}
selectIn(box:HTMLElement,label:string,values:string[],on:(v:string)=>void){const s=box.createEl("select");s.createEl("option",{text:label});values.forEach(v=>s.createEl("option",{text:v,value:v}));s.onchange=()=>on(s.value);return s}
renderQuestion(){if(!this.q)return;const q=this.q,card=this.root.createDiv("sat-question-card");card.createEl("div",{text:`${q.domain}  ·  ${q.skill}`,cls:"sat-question-meta"});card.createEl("div",{text:q.difficulty,cls:"sat-difficulty"});if(q.passage)card.createEl("div",{text:clean(q.passage),cls:"sat-passage"});card.createEl("div",{text:clean(q.questionText),cls:"sat-question-text"});q.choices?.forEach(c=>{const row=card.createEl("button",{text:`${c.key}   ${clean(c.text)}`,cls:"sat-choice"});row.onclick=()=>{row.addClass(c.key===q.correctAnswer?"sat-correct":"sat-wrong");new Notice(c.key===q.correctAnswer?"Correct":"Try again")}});const actions=card.createDiv("sat-actions");const insert=actions.createEl("button",{text:"Insert into note",cls:"sat-insert"});insert.onclick=()=>{const e=this.app.workspace.activeEditor?.editor;if(e){e.replaceSelection(format(q));new Notice("Question inserted into note")}};const next=actions.createEl("button",{text:"↻ Another like this"});next.onclick=()=>{const p=new URLSearchParams({random:"1",limit:"1",domain:q.domain,skill:q.skill});requestUrl({url:`${this.s.apiUrl}/api/questions?${p}`}).then(r=>{this.q=r.json.questions?.[0];this.render()})}}
}
class Tab extends PluginSettingTab{constructor(app:App,private p:SatNexus){super(app,p)}display(){this.containerEl.empty();new Setting(this.containerEl).setName("SAT Nexus URL").setDesc("URL of your deployed website").addText(t=>t.setValue(this.p.settings.apiUrl).onChange(async v=>{this.p.settings.apiUrl=v.replace(/\/$/,"");await this.p.saveData(this.p.settings)}))}}
