import { SATQuestion } from "./types";

export const SEED_QUESTIONS: SATQuestion[] = [
  {
    id: "ac472881",
    questionText: "In the given equation, s and r are constants, and s > 0. If the equation has infinitely many solutions, what is the value of s?\n\n(12x + s)/4 - s/13 = r(x - 8)",
    passage: null,
    imageUrl: null,
    mathExpression: "\\frac{12x+s}{4} - \\frac{s}{13} = r(x-8)",
    choices: undefined,
    correctAnswer: "403",
    explanation: "College Board: (12x+28)/4 = 3x+7 ... 3x + 7 - s/13 = rx - 8r. r=3. 7 - s/13 = -24 => s/13 = 31 => s = 403.",
    difficulty: "Hard",
    domain: "Math",
    skill: "Algebra",
    subskill: "Linear equations in one variable",
    source: "College Board SAT Question Bank",
    tags: ["infinite solutions","algebra"],
    timesAnswered: 0,
    timesCorrect: 0,
    avgResponseMs: undefined,
    mastery: 0,
    lastReviewed: null,
    createdAt: "2025-11-02T00:00:00Z",
    type: "free_response",
    favorite: false
  },
  {
    id: "2937ef4f",
    questionText: "Hector used a tool called an auger to remove corn from a storage bin at a constant rate. The bin contained 24,000 bushels of corn when Hector began to use the auger. After 5 hours of using the auger, 19,350 bushels of corn remained in the bin. If the auger continues to remove corn at this rate, what is the total number of hours Hector will have been using the auger when 12,840 bushels of corn remain in the bin?",
    passage: null,
    imageUrl: null,
    mathExpression: null,
    choices: [
      { key: "A", text: "3" },
      { key: "B", text: "7" },
      { key: "C", text: "8" },
      { key: "D", text: "12" }
    ],
    correctAnswer: "D",
    explanation: "Removed in 5h: 24,000 - 19,350 = 4,650. Rate = 4650/5 = 930 bu/h. 24,000 - 930x = 12,840 → 930x = 11,160 → x = 12.",
    difficulty: "Hard",
    domain: "Math",
    skill: "Algebra",
    subskill: "Linear functions",
    source: "College Board SAT Question Bank",
    tags: ["rate","word problem"],
    timesAnswered: 0,
    timesCorrect: 0,
    avgResponseMs: undefined,
    mastery: 0,
    lastReviewed: null,
    createdAt: "2025-10-14T00:00:00Z",
    type: "multiple_choice",
    favorite: false
  },
  {
    id: "3f5a3602",
    questionText: "What system of linear equations is represented by the lines shown?",
    passage: null,
    imageUrl: "/sat-graph-3f5a3602.svg",
    mathExpression: null,
    choices: [
      { key: "A", text: "8x + 4y = 32\n-10x - 4y = -64" },
      { key: "B", text: "8x + 4y = 32\n-10x + 4y = -64" },
      { key: "C", text: "4x - 10y = 32\n-8x + 10y = -64" },
      { key: "D", text: "4x + 10y = 32\n-8x - 10y = -64" }
    ],
    correctAnswer: "D",
    explanation: "Line 1 passes through (8,0) and (3,4). Slope -4/5, y = -2/5 x + 16/5 → 4x+10y=32. Line 2 passes through (8,0) and (3,2). Slope -2/5 → 2x+5y=16 → -8x-10y=-64.",
    difficulty: "Hard",
    domain: "Math",
    skill: "Algebra",
    subskill: "Systems of two linear equations in two variables",
    source: "College Board SAT Question Bank",
    tags: ["graph","systems"],
    timesAnswered: 0,
    timesCorrect: 0,
    avgResponseMs: undefined,
    mastery: 0,
    lastReviewed: null,
    createdAt: "2025-09-21T00:00:00Z",
    type: "multiple_choice",
    favorite: false
  }
];
