import json

# Merriam-Webster-aligned senses (2-3 distinct senses per word where applicable).
# The first sense becomes the primary `definition`; all senses go in `definitions`.
MW = {
 "abate": ["to decrease in force or intensity", "to reduce in degree, amount, or value", "to put an end to; nullify (as in law)"],
 "ambivalent": ["having simultaneous and contradictory attitudes or feelings toward something", "characterized by uncertainty or indecisiveness about which course to follow"],
 "bolster": ["to support with or as if with a long pillow or cushion", "to give a boost to; reinforce or strengthen"],
 "corroborate": ["to support with evidence or authority; make more certain", "to confirm or give fresh support to a claim, theory, or finding"],
 "delineate": ["to describe, portray, or set forth with accuracy or in detail", "to indicate or represent by drawn or painted lines", "to mark the outline or boundaries of"],
 "empirical": ["originating in or based on observation or experience", "relying on experience or observation alone, often without regard for system or theory", "capable of being verified or disproved by observation or experiment"],
 "equivocal": ["subject to two or more interpretations and usually used to mislead or confuse", "uncertain or doubtful in nature; of uncertain outcome"],
 "exacerbate": ["to make more violent, bitter, or severe", "to make a bad situation, an injury, or a problem worse"],
 "infer": ["to derive as a conclusion from facts or premises", "to guess or surmise from available information", "to suggest or hint indirectly; imply"],
 "mitigate": ["to cause to become less harsh or hostile; mollify", "to make less severe or painful; alleviate", "to lessen the seriousness or extent of"],
 "nuance": ["a subtle distinction or variation", "a subtle quality; a delicate shading of meaning, feeling, or tone", "sensibility to or awareness of such fine-grained differences"],
 "pragmatic": ["relating to matters of fact or practical affairs, often to the exclusion of intellectual or artistic matters", "practical as opposed to idealistic; concerned with workable solutions"],
 "refute": ["to prove wrong by argument or evidence; show to be false or erroneous", "to deny the truth or accuracy of"],
 "substantiate": ["to establish by proof or competent evidence; verify", "to give substance or concrete form to; embody"],
 "ubiquitous": ["existing or being everywhere at the same time; constantly encountered", "widespread; seeming to be present wherever one looks"],
 "authority": ["the power to issue commands, make decisions, and enforce obedience", "a person or organization having power or control in a particular sphere", "an accepted source of expert information or advice"],
 "aspect": ["a particular part or feature of something being considered", "a particular way in which something appears or may be regarded", "the appearance or expression of a person or thing"],
 "impact": ["a forceful striking of one body against another; collision", "a significant or major effect or influence", "the force of impression of one thing on another"],
 "candidate": ["a person who seeks or is nominated for an office, prize, or honor", "a person or thing regarded as suitable for or likely to experience a particular fate, treatment, or position"],
 "obtain": ["to gain or attain, usually by planned action or effort", "to be generally recognized, established, or in effect; prevail"],
 "repertoire": ["the complete list of works that a performer or company is prepared to present", "the full range of skills, techniques, or devices used in a particular field or practice"],
 "distribution": ["the act or process of dividing and giving out among a number of recipients", "the position, arrangement, or frequency of occurrence over an area or throughout a space", "the marketing and supplying of goods, especially to retailers"],
 "regime": ["a form of government or the government in power", "a regular pattern of occurrence or action; a regulated system or plan (as of diet or exercise)"],
 "acid": ["a chemical compound that yields hydrogen ions in solution, tastes sour, and turns litmus red", "sharp, biting, or sour in taste or manner; caustic"],
 "transaction": ["an exchange or transfer of goods, services, or funds", "a communicative action or activity involving two parties that reciprocally affect each other", "the act or process of carrying out or conducting business"],
 "dynamic": ["marked by usually continuous and productive activity or change; energetic or forceful", "relating to physical force or energy in motion", "an underlying pattern of change, growth, or interaction between elements of a system"],
 "strategic": ["of, relating to, or marked by a careful overall plan for achieving a goal", "necessary to or important in the initiation, conduct, or completion of a plan", "designed or trained to strike an enemy at the sources of its power"],
 "contrary": ["a fact or condition that is completely different or opposite", "being exactly opposite in nature, direction, or meaning", "temperamentally unwilling to accept control or advice; perverse"],
 "exploit": ["a notable, memorable, or heroic act or deed", "to make productive use of; utilize", "to make unfair or selfish use of for one's own advantage"],
 "bargain": ["an agreement between parties settling what each gives or receives in a transaction", "something acquired at an advantageous price; a good deal", "to negotiate over the terms of an agreement"],
 "dominant": ["commanding, controlling, or prevailing over all others", "overlooking from a superior position or elevation", "of a gene: expressed even when only one copy is present"],
 "cure": ["recovery or relief from a disease", "something (as a drug or treatment) that restores health or corrects a harmful situation", "to prepare or preserve (as meat or fish) by drying, salting, or aging"],
 "execute": ["to carry out fully; put completely into effect", "to put to death in accordance with a legally imposed sentence", "to perform or produce (as a work of art or a skilled action)"],
 "conscious": ["perceiving or noticing with a degree of controlled thought or observation; aware", "done or acting with critical awareness; intentional", "having mental faculties not dulled by sleep, faintness, or stupor; awake"],
 "consent": ["to give assent or approval; agree", "compliance in or approval of what is done or proposed by another; permission"],
 "interval": ["a space of time between events or states", "a space between objects, units, or points", "the difference in pitch between two musical tones"],
 "scenario": ["an outline or synopsis of a play, film, or other dramatic work", "a sequence of events especially when imagined or projected", "an account or description of a possible course of action or events"],
 "outlet": ["a place or opening through which something is let out; an exit or vent", "a means of release or expression for an emotion, impulse, or ability", "a store through which products are sold; a receptacle for electrical connection"],
 "architect": ["a person who designs buildings and advises in their construction", "a person who designs and guides a plan, project, or undertaking"],
 "controversy": ["a discussion marked especially by the expression of opposing views; dispute", "a state of prolonged public argument or quarrel"],
 "feedback": ["the transmission of evaluative or corrective information about an action or process to the original source", "helpful information or criticism given to improve performance", "the return of part of a system's output to its input, as in an electronic circuit"],
 "render": ["to transmit or deliver to another; to give in return or requital", "to cause to be or become; make", "to reproduce, represent, or depict by artistic or verbal means"],
 "puzzle": ["to offer or represent a problem difficult to solve; to confuse or perplex", "a question, problem, or contrivance designed for testing ingenuity", "something that baffles understanding; an enigma"],
 "classify": ["to arrange in classes or categories according to shared characteristics", "to assign to a category", "to designate (information) as requiring secrecy"],
 "scatter": ["to cause to separate widely and go in various directions", "to distribute irregularly or at intervals", "to diffuse or disperse (as a beam of radiation) in many directions"],
 "treaty": ["an agreement or arrangement made by negotiation, especially a contract between two or more states", "a formal document embodying such an international agreement"],
 "diverse": ["differing from one another; unlike", "composed of distinct or unlike elements or qualities", "including people of different races, cultures, or backgrounds"],
 "alliance": ["an association to further the common interests of the members", "a bond or connection between families, states, parties, or individuals", "the state of being joined in such an association"],
 "clue": ["something that guides through an intricate procedure or maze of difficulties", "a piece of evidence that leads one toward the solution of a problem"],
 "evident": ["clear to the vision or understanding; plain or obvious"],
 "virtue": ["conformity to a standard of right; a particular moral excellence", "a beneficial or commendable quality or trait; merit", "a capacity to act; potency or effective power"],
 "observer": ["a person who watches, notices, or pays attention to something", "a person sent to watch proceedings (as at a conference) without participating officially", "an expert commentator on a particular field or situation"],
 "entity": ["something that has separate and distinct existence and objective or conceptual reality", "an organization (as a business or government unit) that has an identity separate from those of its members"],
 "facilitate": ["to make (something) easier; to help bring about"],
 "induce": ["to move by persuasion or influence", "to cause to happen or bring about by influence or stimulation", "to arrive at (a general conclusion) by reasoning from particular instances"],
 "indicator": ["a sign, pointer, or index that shows the condition or existence of something", "a device or instrument that displays a measurement or state", "a statistic that measures the health of an economy or system"],
 "necessity": ["the quality or state of being required; indispensability", "something that is indispensable", "pressure of circumstance or physical constraint; great need"],
 "drain": ["to draw off (liquid) gradually or completely", "to exhaust or deplete gradually (as strength or resources)", "a means (as a pipe or channel) by which usually liquid matter is drawn off"],
 "audit": ["a formal examination of an organization's or individual's accounts or financial situation", "a methodical examination and review", "to attend (a course) without working for credit"],
 "consensus": ["general agreement; unanimity", "the judgment arrived at by most of those concerned", "group solidarity in sentiment and belief"],
 "reinforce": ["to strengthen by additional assistance, material, or support", "to strengthen or increase by fresh additions", "to stimulate (a response) with a reward so that it becomes more likely to recur"],
 "valid": ["having legal efficacy or force; executed according to law", "well-grounded or justifiable; logically correct", "appropriate to the end in view; effective"],
 "collective": ["denoting a number of persons or things considered as one group or whole", "shared, done, or involving all members of a group", "a cooperative unit or organization owned and operated by its members"],
 "proposition": ["something offered for consideration or acceptance; a proposal", "an expression in language or signs of something that can be believed, doubted, or denied", "a project, situation, or matter to be dealt with"],
 "parameter": ["a quantity whose value characterizes a system or sets the conditions of its operation", "any of a set of physical properties whose values determine the characteristics or behavior of something", "a limit or boundary; a characteristic element"],
 "terminal": ["of or relating to an end, extremity, boundary, or terminus", "leading ultimately to death; fatal", "a station at the end of a transportation line; a device for entering data into or displaying data from a computer"],
 "interrupt": ["to stop or hinder by breaking in on", "to break the uniformity or continuity of", "to break in upon an action or speech"],
 "fiber": ["a thread or a structure or object resembling a thread", "plant material that is not digested but aids digestion; roughage", "essential structure, character, or strength"],
 "precede": ["to be, go, or come ahead or in front of", "to surpass in rank, dignity, or importance", "to come before in time"],
 "drift": ["to become driven or carried along by a current of water, wind, or air", "to move or wander aimlessly or without purpose", "a general underlying tendency, meaning, or purport"],
 "expertise": ["the skill or knowledge of an expert", "expert opinion or commentary"],
 "elite": ["the choice part or best of a class, group, or society", "a group of persons who by virtue of position or education exercise much power or influence", "of or being the best or most privileged group"],
 "confine": ["to keep within limits; restrict", "to hold within a location; imprison", "something (as borders or walls) that encloses; bounds"],
 "stimulus": ["something that rouses or incites to activity; an incentive", "an agent (as an environmental change) that directly influences the activity of a living organism or one of its parts", "government measures intended to encourage economic activity"],
 "elaborate": ["planned or carried out with great care; worked out in detail", "marked by complexity, fullness of detail, or ornateness", "to expand on something in detail; to work out carefully"],
 "manual": ["of, relating to, or involving the hands", "requiring or using physical skill and energy; done or operated by hand rather than by machine", "a book that is conveniently handled, especially one giving instructions"],
 "particle": ["a minute quantity or fragment", "a relatively small or the smallest discrete portion or amount of something", "any of the basic units of matter and energy (as an electron or photon)"],
 "initiate": ["to cause or facilitate the beginning of; set going", "to induct into membership by or as if by special rites", "to instruct in the rudiments or principles of something"],
 "fluid": ["a substance (as a liquid or gas) tending to flow or conform to the outline of its container", "having a smooth, easy style or movement; graceful", "subject to change or movement; not fixed or settled"],
 "discrimination": ["prejudiced or prejudicial outlook, action, or treatment based on category rather than individual merit", "the act or power of distinguishing finely; discernment", "the process by which two stimuli differing in some aspect are responded to differently"],
 "coordinate": ["to bring into a common action, movement, or condition; harmonize", "equal in rank, quality, or significance", "any of a set of numbers used to specify the location of a point"],
 "sensible": ["having, containing, or indicative of good sense or reason; rational", "perceptible to the senses or to reason or understanding", "aware of or responsive to something"],
 "fabric": ["a cloth made by weaving, knitting, or felting fibers", "the underlying structure or framework of something", "the arrangement of physical components in relation to each other"],
 "spectrum": ["a band of colors produced when light is dispersed, as by a prism", "a continuous sequence or range arranged in order of a varying characteristic", "the full range of electromagnetic frequencies or of some other measurable property"],
 "grasp": ["to take or seize eagerly; clasp or embrace with the fingers or arms", "to lay hold of with the mind; comprehend", "the power of seizing and holding; reach or comprehension"],
 "rhythm": ["an ordered recurrent alternation of strong and weak elements in the flow of sound and silence in speech or music", "movement or fluctuation marked by the regular recurrence of elements", "a regularly recurrent quantitative change in a variable biological process"],
 "ritual": ["the established form for a ceremony", "a ceremonial act or action; a system of rites", "an act or series of acts regularly repeated in a set precise manner"],
 "intensity": ["the quality or state of existing in an extreme degree; extreme strength or force", "extreme depth of feeling or conviction", "the magnitude of a quantity (as energy or force) per unit (as of area or time)"],
 "assert": ["to state or declare positively and often forcefully", "to demonstrate the existence of; to defend or maintain (as one's rights)", "to compel or demand acceptance or recognition of (as one's authority)"],
 "span": ["the full extent, stretch, or reach of something from end to end", "a limited period of time", "to extend across or over"],
 "undermine": ["to weaken or ruin by degrees; to subvert secretly or insidiously", "to wash away or wear away supporting material from beneath"],
 "comply": ["to conform, submit, or adapt (as to a regulation or another's wishes) as required or requested"],
 "tempt": ["to entice to do wrong by promise of pleasure or gain", "to induce or provoke to do something; to be attractive to", "to risk provoking (as fate or danger)"],
 "faculty": ["an inherent mental or physical power or ability", "the teaching and administrative staff of an educational institution", "one of the divisions of a university"],
 "depict": ["to represent by or as if by a picture", "to describe or portray in words"],
 "clarify": ["to make (something) understandable; free of confusion", "to make (a liquid or something viscous) clear or pure, usually by freeing from suspended matter"],
 "colony": ["an area over which a foreign nation extends or maintains control, or the body of settlers living there", "a group of individuals or organisms of one kind living together in close association", "a group of people with common characteristics or interests situated in close association"],
 "motive": ["something (as a need or desire) that causes a person to act", "a recurrent phrase, figure, or theme that is elaborated on in a work of art or music"],
 "tribe": ["a social group comprising numerous families, clans, or generations together with dependents or adopted strangers", "a group of persons having a common character, occupation, or interest", "a category of biological classification ranking between family and genus"],
 "minimize": ["to reduce or keep to a minimum", "to underestimate intentionally; play down or soft-pedal", "to represent at less than true value"],
 "plug": ["a piece used to fill or close a hole; a stopper", "a device for making an electrical connection", "to publicize insistently; to work doggedly and persistently"],
 "strand": ["one of the fibers, threads, or wires twisted or plaited together into a rope, cord, or yarn", "an elongated or twisted and plaited body resembling a rope", "to leave in a strange or unfavorable place, especially without means of departing"],
 "discourse": ["verbal interchange of ideas; conversation", "formal and orderly and usually extended expression of thought on a subject", "a mode of organizing knowledge, ideas, or experience rooted in language"],
 "legitimate": ["accordant with law or with established legal forms and requirements; lawful", "conforming to recognized principles or accepted rules and standards", "being exactly as intended or presented; neither spurious nor false"],
 "bound": ["fastened by or as if by a band; confined or obliged", "a limiting line or boundary; a limit beyond which one cannot go", "to move by leaping; a leap or jump"],
 "norm": ["an authoritative standard; a model", "a principle of right action binding upon members of a group", "a widespread or usual practice, procedure, or custom; average"],
 "allocate": ["to apportion for a specific purpose or to particular persons or things; distribute", "to set apart or earmark; designate"],
 "rational": ["having reason or understanding", "relating to, based on, or agreeable to reason; reasonable", "of a number: expressible as the quotient of two integers"],
 "resemble": ["to correspond to in appearance or superficial qualities; be like or similar to"],
 "probe": ["a slender instrument or device used to explore, examine, or measure", "a penetrating or critical investigation", "to search into and explore very thoroughly"],
 "harvest": ["the season for gathering in agricultural crops, or the act of gathering them", "a mature crop (as of grain or fruit); yield", "an accumulated store or productive result"],
 "cognitive": ["of, relating to, being, or involving conscious intellectual activity (as thinking, reasoning, or remembering)", "based on or capable of being reduced to empirical factual knowledge"],
 "subtle": ["delicate or elusive in meaning or quality; difficult to perceive or analyze", "perceptive, refined, or discriminating in thought", "operating in a hidden, clever, or crafty way"],
 "merge": ["to cause to combine, unite, or coalesce into one", "to blend or come together gradually without abrupt change", "to be absorbed into or swallowed up by something larger"],
 "legend": ["a story coming down from the past, especially one popularly regarded as historical although not verifiable", "a person or thing that inspires such stories; one of extraordinary fame", "an explanatory list of the symbols on a map or chart; an inscription or title"],
 "hedge": ["a fence or boundary formed by a dense row of shrubs or low trees", "a means of protection or defense, especially against financial loss", "to avoid committing oneself to a definite course of action"],
 "bulk": ["magnitude in three dimensions; great size or volume", "the main or greater part of something", "to appear as a factor of great importance; loom large"],
 "discharge": ["to release from an obligation, confinement, or care", "to shoot or fire (a weapon); to emit or pour forth", "to perform and complete (a duty or function); to unload"],
 "swell": ["to expand gradually beyond a normal or original limit", "to become distended or puffed up", "a long, often massive, crestless wave or succession of waves"],
 "transmit": ["to send or convey from one person or place to another", "to cause or allow to spread, as an infection or a trait passed to offspring", "to send out (a signal) by radio waves or over a wire"],
 "stack": ["a large, usually conical pile (as of hay or grain); an orderly pile or heap", "to arrange in a pile or heap", "to arrange secretly for cheating; to load unfairly"],
 "explicit": ["fully revealed or expressed without vagueness or ambiguity; leaving no question as to meaning", "fully developed or formulated; unreserved and unambiguous in expression", "open in the depiction of sexuality or violence"],
 "essence": ["the permanent as contrasted with the accidental element of being; the real or ultimate nature of a thing", "the most significant element, quality, or aspect of a thing or person", "a concentrated extract or preparation (as of a plant) containing its fundamental properties"],
 "progressive": ["making use of or interested in new ideas, findings, or opportunities; favoring gradual political reform", "moving forward or onward; advancing", "increasing in extent or severity, as a disease; increasing in rate as the base increases, as a tax"],
 "interfere": ["to come into collision or be in opposition; to run at cross-purposes", "to interpose in a way that hinders or impedes; meddle", "to affect one another, as sound or light waves do"],
 "surplus": ["the amount that remains when use or need is satisfied; an excess of receipts over disbursements"],
 "bundle": ["a group of things fastened together for convenient handling", "a considerable number or amount; a sizable sum of money", "to hurry or move quickly and unceremoniously; to wrap or package tightly"],
 "accelerate": ["to move faster; to gain speed", "to bring about at an earlier time; to hasten the progress or development of", "to cause to undergo an increase in velocity"],
 "defect": ["an imperfection or abnormality that impairs quality, function, or utility; a shortcoming or flaw", "to forsake one cause, party, or nation for another, often for reprehensible reasons"],
 "portray": ["to make a picture of; depict", "to describe in words", "to play the role of; enact"],
 "thread": ["a filament or a group of filaments twisted together, formed by spinning and twisting short fibers", "an elemental, pervading, or connecting element that runs through something (as a story or argument)", "to pass a thread through; to make one's way carefully through or between"],
 "stance": ["a way of standing or being placed; posture", "an intellectual or emotional attitude; a publicly stated position"],
 "competence": ["the quality or state of having sufficient knowledge, judgment, skill, or strength; ability", "the legal authority, ability, or admissibility to act or be heard", "sufficient income or means for the necessities of life"],
 "intervene": ["to come between disputing parties in order to settle or change events; interfere with an outcome", "to occur, fall, or come between points of time or events", "to enter or appear as an irrelevant or extraneous feature or circumstance"],
 "sketch": ["a rough drawing representing the chief features of an object or scene, often made as a preliminary study", "a brief description or outline giving essential facts", "a short, often comic, theatrical piece; to draw or outline roughly"],
 "profound": ["having intellectual depth and insight; difficult to fathom or understand", "extending far below the surface; coming from a depth", "characterized by intensity of feeling or quality; all-encompassing or complete"],
 "incline": ["to bend the head or body forward; to lean, tend, or become drawn toward an opinion or course of conduct", "to deviate from the vertical or horizontal; slope", "a surface that slopes; a grade"],
 "commodity": ["an economic good, such as an agricultural product or a mined raw material, that can be bought and sold", "a mass-produced unspecialized product", "something useful or valued; a convenience or advantage"],
 "prejudice": ["preconceived judgment or opinion; an adverse opinion formed without just grounds or sufficient knowledge", "an irrational attitude of hostility directed against an individual, group, or race", "injury or damage resulting from a judgment or action of another, especially in law"],
 "obscure": ["not readily understood or clearly expressed; ambiguous or vague", "relatively unknown; remote or secluded", "to conceal or hide by or as if by covering"],
 "neutral": ["not engaged on either side; not aligned with a political or ideological grouping", "having no strongly marked or positive characteristics or features; a color without hue", "neither acid nor basic; having no electrical charge"],
 "compensate": ["to make an appropriate payment to; to make amends for loss, injury, or service rendered", "to counterbalance or offset an error, defect, or undesired effect", "to supply an equivalent for; to be equivalent to in value or effect"],
 "accumulate": ["to gather or pile up, especially little by little; amass", "to increase gradually in quantity or number"],
 "utilize": ["to make use of; turn to practical use or account"],
 "pulse": ["the regular expansion of an artery caused by the ejection of blood into it by contractions of the heart", "a rhythmical beating, vibrating, or sounding; a brief sudden change in a normally constant quantity", "the underlying sentiment or feeling of a group or public"],
 "embed": ["to enclose closely in or as if in a surrounding mass; to set solidly in or as if in a matrix", "to make something an integral part of a larger whole", "to insert (media or code) into a document or program"],
 "aggregate": ["formed by the collection of units or particles into a body, mass, or amount; collective or total", "a mass or body of units or parts somewhat loosely associated with one another; the whole sum or amount", "to collect or gather into a mass or whole; to amount to"],
 "activate": ["to make active or more active; set in motion", "to make (a substance) radioactive, chemically reactive, or capable of a specific biological response", "to put (a military unit) on active status"],
 "conceive": ["to become pregnant with (young)", "to take into one's mind; to form a conception of; imagine", "to apprehend by reason or imagination; understand or believe"],
 "manipulate": ["to treat or operate with or as if with the hands or by mechanical means, especially in a skillful manner", "to manage or utilize skillfully", "to control or play upon by artful, unfair, or insidious means, especially to one's own advantage"],
 "articulate": ["expressing oneself readily, clearly, and effectively", "to give clear and effective utterance to; to put into words", "to unite by or as if by a joint; consisting of segments united by joints"],
 "presume": ["to suppose to be true without proof", "to undertake without leave or clear justification; dare", "to take for granted; to act or proceed on the assumption that something is true"],
 "chronic": ["continuing or occurring again and again for a long time; marked by long duration or frequent recurrence", "always present or encountered; constantly vexing, weakening, or troubling", "habitual; being such by habit"],
 "acute": ["marked by keen discernment or intellectual perception; sharp or penetrating", "having a sudden onset, sharp rise, and short course, as an illness", "of an angle: measuring less than 90 degrees"],
 "trait": ["a distinguishing quality of personal character", "an inherited characteristic", "a distinguishing feature, as of appearance or habit"],
 "compact": ["occupying a small volume by reason of efficient use of space; closely and firmly packed together", "an agreement or covenant between two or more parties", "to press or squeeze together; make more dense"],
 "instinct": ["a natural or inherent aptitude, impulse, or capacity", "a largely inheritable and unalterable tendency of an organism to make a complex and specific response to environmental stimuli without involving reason", "behavior originating below the conscious level"],
 "metaphor": ["a figure of speech in which a word or phrase denoting one kind of object or idea is used in place of another to suggest a likeness between them", "an object, activity, or idea treated as a symbol of something else"],
 "closure": ["an act of closing or the condition of being closed", "a feeling of finality or resolution, as after a traumatic experience", "a device (as a cap or seal) that closes or shuts"],
 "dilemma": ["a situation requiring a choice between equally undesirable alternatives", "a difficult or persistent problem", "an argument presenting an antagonist with two or more alternatives, each conclusive against him"],
 "diagnose": ["to recognize (as a disease) by signs and symptoms", "to analyze the cause or nature of a problem or situation"],
 "stereotype": ["a standardized mental picture held in common by members of a group that represents an oversimplified opinion, prejudiced attitude, or uncritical judgment", "something conforming to a fixed or general pattern", "to develop a fixed, oversimplified image of"],
 "threshold": ["the plank, stone, or piece of timber that lies under a door; a doorsill", "the point of entering or beginning; outset", "the point or level at which a physical or psychological effect begins to be produced"],
 "dictate": ["to speak or read for a person to transcribe or for a machine to record", "to issue as an order; to impose, pronounce, or specify authoritatively", "a ruling principle or authoritative rule or injunction"],
 "adjacent": ["not distant; nearby; having a common border", "immediately preceding or following", "of two angles: having the vertex and one side in common"],
 "specimen": ["an individual, item, or part considered typical of a group, class, or whole", "a portion or quantity of material for use in testing, examination, or study"],
 "hierarchy": ["the classification of a group of people according to ability or to economic, social, or professional standing", "a graded or ranked series", "a ruling body organized into orders or ranks each subordinate to the one above it"],
 "rhetoric": ["the art of speaking or writing effectively", "language that is calculated to produce an effect, especially insincere or grandiloquent language", "skill in the effective use of speech"],
 "matrix": ["something within or from which something else originates, develops, or takes form", "a mold from which a relief surface is made; the natural material in which something (as a fossil or gem) is embedded", "a rectangular array of mathematical elements subject to special algebraic laws"],
 "vein": ["any of the tubular vessels that carry blood from the capillaries toward the heart", "a bed of useful mineral matter; a streak or marking (as in marble or wood)", "a distinctive mode of expression; a style, quality, or strain"],
 "complement": ["something that fills up, completes, or makes better or perfect", "the full quantity, number, or assortment needed or included", "the angle that when added to a given angle equals 90 degrees"],
 "crude": ["existing in a natural state and unaltered by cooking or processing; raw", "marked by the primitive, gross, or elemental; lacking refinement, grace, or tact", "rough or inexpert in plan or execution"],
 "vague": ["not clearly expressed; stated in indefinite terms", "not having a precise meaning; not clearly defined, grasped, or understood", "not thinking or expressing one's thoughts clearly or precisely; hazy or indistinct"],
 "differentiate": ["to mark or show a difference in; to become distinct or different in character", "to recognize or state the difference between; discriminate", "to undergo change toward a more specialized form or function, as cells do"],
 "noble": ["possessing outstanding qualities; having or showing greatness of character; magnanimous", "of or relating to high birth or exalted rank; aristocratic", "grand or impressive especially in appearance; chemically inert or inactive, as a gas"],
 "lump": ["a piece or mass of indefinite size and shape", "an abnormal swelling or protuberance", "to group together indiscriminately"],
 "limb": ["one of the projecting paired appendages of an animal body used especially for movement and grasping; an arm, leg, or wing", "a large primary branch of a tree", "an active member or agent; an extension or branch"],
 "autonomy": ["the quality or state of being self-governing; self-directing freedom and especially moral independence", "a self-governing state"],
 "realm": ["a kingdom", "a sphere or domain within which something occurs or dominates"],
 "definite": ["having distinct or certain limits", "free of all ambiguity, uncertainty, or obscurity; unquestionable or decided", "typically designating an identified or immediately identifiable person or thing"],
 "dense": ["marked by compactness or crowding together of parts", "slow to understand; thickheaded or stupid", "demanding concentration to follow or comprehend"],
 "dissolve": ["to cause to pass into solution; to melt or liquefy", "to bring to an end; terminate or annul, as an assembly or agreement", "to fade away; to break into component parts or disintegrate"],
 "magnitude": ["great size or extent", "the importance, quality, or caliber of something", "a number representing the intrinsic or apparent brightness of a celestial body, or the intensity of an earthquake"],
 "adverse": ["acting against or in a contrary direction; hostile", "opposed to one's interests; unfavorable or harmful"],
 "shallow": ["having little depth", "lacking in depth of knowledge, thought, or feeling; superficial", "a shallow place in a body of water"],
 "indirect": ["not direct; deviating from a straight line or course; roundabout", "not going straight to the point; not straightforward or open", "not resulting directly from an action or cause; secondary"],
 "maximize": ["to increase to a maximum; to make the most of", "to find the largest value of a mathematical function", "to assign the highest possible importance to"],
 "competent": ["having requisite or adequate ability or qualities; fit or capable", "legally qualified or adequate", "proper or rightly pertinent; sufficient"],
 "damp": ["slightly or moderately wet; moist", "moisture; humidity or vapor", "to lessen the activity, force, or intensity of"],
 "momentum": ["the property that a moving body has due to its mass and motion, equal to the product of the two", "strength or force gained by motion or by a series of events; impetus"],
 "marginal": ["written or printed in the margin of a page or sheet", "of secondary or minor importance; not central", "close to the lower limit of qualification, acceptability, or function; barely adequate"],
 "tolerance": ["capacity to endure pain or hardship; endurance or stamina", "sympathy or indulgence for beliefs or practices differing from or conflicting with one's own", "the allowable deviation from a standard; the body's decreasing response to repeated doses of a substance"],
 "habitat": ["the place or environment where a plant or animal naturally or normally lives and grows", "the typical place of residence of a person or group", "a housing for a controlled physical environment in which people can live under inhospitable conditions"],
 "elevate": ["to lift up or make higher; raise", "to raise in rank or status; exalt", "to improve morally, intellectually, or culturally; to raise the spirits of"],
 "viable": ["capable of living, growing, or developing, as a fetus or seed", "capable of working, functioning, or succeeding; practicable", "having a reasonable chance of succeeding"],
 "bizarre": ["strikingly out of the ordinary, as in odd extravagance or incongruity; fantastic or grotesque"],
 "impulse": ["a sudden spontaneous inclination or incitement to some usually unpremeditated action", "a force so communicated as to produce motion suddenly; a wave of excitation transmitted through a nerve", "a propensity or natural tendency, usually other than rational"],
 "pardon": ["the excusing of an offense without exacting a penalty; a release from the legal penalties of an offense", "to forgive or excuse for a fault or offense"],
 "toxic": ["containing or being poisonous material; capable of causing serious injury or death", "extremely harsh, malicious, or harmful, as a relationship or environment"],
 "illusion": ["a misleading image presented to the vision; something that deceives or misleads intellectually", "perception of something objectively existing in such a way as to cause misinterpretation of its actual nature", "the state or fact of being intellectually deceived or misled"],
 "pathway": ["a path, course, or track along which something moves", "the sequence of enzyme-catalyzed reactions by which a substance is converted into another in a living organism"],
 "unify": ["to make into a unit or a coherent whole; unite"],
 "swap": ["to give in trade; barter or exchange", "an act, instance, or agreement of exchanging one thing for another"],
 "gravity": ["the gravitational attraction of the mass of a celestial object (as earth) for bodies at or near its surface", "dignity or sobriety of bearing; seriousness", "significance, especially of a grave or dangerous kind"],
 "athletic": ["of or relating to athletes or athletics", "characterized by or befitting skill, strength, or vigorous activity", "having a muscular, well-developed build"],
 "aesthetic": ["of, relating to, or dealing with the beautiful or with the appreciation of beauty", "pleasing in appearance; artistic", "a particular theory or conception of beauty or art; a distinctive style or sensibility"],
 "irrelevant": ["not applicable or pertinent; not relating to the subject at hand"],
 "contradiction": ["the act of denying or saying the opposite of a statement made by another", "a proposition, statement, or phrase that asserts or implies both the truth and falsity of something", "opposition or inconsistency between two or more elements"],
 "orient": ["to set or arrange in a definite position, especially in relation to the points of the compass", "to acquaint with an existing situation or environment; to familiarize", "to direct toward the interests of a particular group or purpose"],
 "monopoly": ["exclusive ownership or control through legal privilege, command of supply, or concerted action", "exclusive possession or control of something", "a commodity controlled by one party, or the entity that has such control"],
 "protocol": ["a code prescribing strict adherence to correct etiquette and precedence, as in diplomatic exchange", "a detailed plan of a scientific or medical experiment, treatment, or procedure", "a set of conventions governing the treatment and formatting of data, as in electronic communications"],
 "primitive": ["of or relating to the earliest age or period; original or ancient", "closely approximating an early ancestral type; little evolved or elemental", "simple, crude, or unsophisticated; produced by a self-taught artist"],
 "inhibit": ["to prohibit from doing something; to hold in check or restrain", "to discourage from free or spontaneous activity, especially through psychological or social controls", "to decrease the rate of a bodily process or chemical reaction, or stop it entirely"],
 "multiply": ["to increase in number, especially greatly or in multiples", "to perform the mathematical operation of multiplication", "to produce offspring; breed or propagate"],
 "parcel": ["a wrapped bundle; a package", "a tract or plot of land", "to divide into parts and distribute"],
 "offspring": ["the product of the reproductive processes of an animal or plant; young or progeny", "a product or result of something"],
 "prey": ["an animal taken by a predator as food", "one that is helpless or unable to resist attack; a victim", "to seize, devour, or have a harmful or wearing effect on something"],
 "valve": ["a structure (as in a vein) that closes temporarily to prevent the return flow of a body fluid", "a mechanical device by which the flow of liquid, gas, or loose material may be regulated", "one of the pieces into which the shell of a mollusk divides"],
 "shuttle": ["a device used in weaving to pass the thread of the weft back and forth between the threads of the warp", "a vehicle or route used to travel back and forth over an established, often short, course", "to move or travel back and forth frequently"],
 "integral": ["essential to completeness; constituent, or formed as a unit with another part", "composed of constituent parts making a whole", "lacking nothing essential; entire"],
 "decay": ["to undergo decomposition; rot", "to decline gradually in health, strength, soundness, or prosperity", "a gradual decrease in quantity or activity, as the spontaneous disintegration of a radioactive substance"],
 "inequality": ["the quality of being unequal or uneven; an instance of disparity", "social disparity or lack of equal treatment or opportunity", "a formal statement that two mathematical quantities are unequal"],
 "artifact": ["a usually simple object (as a tool or ornament) made or modified by human workmanship, especially one of historical interest", "something characteristic of or resulting from a particular human institution, period, or activity", "a product of artificial character (as in a scientific test) due to an outside agency or action"],
 "selective": ["of, relating to, or characterized by careful choice; judicious or restrictive in choosing", "highly specific in activity or effect, as a drug or process"],
 "stripe": ["a line or long narrow section differing in color or texture from parts adjoining", "a piece of braid worn on a uniform sleeve to indicate rank or length of service", "a distinct variety, sort, or type; character"],
 "utterance": ["something uttered; a spoken or written statement", "vocal expression; the act of speaking", "power, style, or manner of speaking"],
 "problematic": ["posing a problem; difficult to solve or decide", "not definite or settled; uncertain or debatable", "open to question or objection"],
 "liable": ["obligated according to law or equity; responsible", "exposed or subject to some usually adverse contingency or action", "likely, especially to do something undesirable"],
 "cord": ["a long slender flexible material usually consisting of several strands woven or twisted together", "an anatomical structure resembling a cord, as the spinal cord or umbilical cord", "a moral, spiritual, or emotional bond"],
 "denote": ["to serve as an indication of; betoken", "to serve as an arbitrary mark for", "to mean or name directly; to stand for as a designation"],
 "static": ["exerting force by reason of weight alone without motion", "showing little change; lacking movement, animation, or progression", "electrical disturbances or the noise they produce in a radio or television system"],
 "axis": ["a straight line about which a body or a geometric figure rotates or may be supposed to rotate", "a straight line with respect to which a body or figure is symmetrical; a reference line of a coordinate system", "a partnership or alliance, especially between countries"],
 "fringe": ["an ornamental border consisting of short straight or twisted threads", "something resembling a border or edge; a periphery", "a group with marginal or extremist views or practices"],
 "spontaneous": ["proceeding from natural feeling or native tendency without external constraint; arising from momentary impulse", "developing or occurring without apparent external influence, force, cause, or treatment", "not apparently contrived or manipulated; natural"],
 "fusion": ["the act or process of melting or making plastic by heat", "a union by or as if by melting; a merging of diverse elements into a unified whole", "the union of atomic nuclei to form heavier nuclei, releasing enormous quantities of energy"],
 "correlate": ["to bear reciprocal or mutual relation; to be in correspondence", "to establish a mutual or reciprocal relation between; to show a connection between", "either of two things so related that one directly implies the other"],
 "onset": ["an attack or assault", "a beginning or commencement, especially of something unpleasant"],
 "retrieve": ["to get back again; regain", "to locate and bring in (killed or wounded game), as a dog does", "to recover or restore (as stored information) from a device or source"],
 "graph": ["a diagram that represents the variation of a variable in comparison with that of one or more other variables", "a collection of vertices and connecting edges studied in mathematics", "to plot or represent by a diagram"],
}
