MW3 = {
 "publish": ["to disseminate to the public; to produce or release for distribution, especially in printed or digital form", "to make generally known; to announce publicly"],
 "conference": ["a meeting of two or more persons for discussing matters of common concern", "a usually formal interchange of views; consultation", "an association of athletic teams; a meeting of members of the two branches of a legislature to adjust differences"],
 "client": ["a person who engages the professional advice or services of another", "a customer; a person served by or utilizing the services of a social agency", "a computer or program that can make use of the resources of a server"],
 "incredible": ["too extraordinary and improbable to be believed", "amazing or extraordinary"],
 "correctly": ["in a manner free from error; accurately", "in a way that conforms to an approved or conventional standard; properly"],
 "painful": ["causing or feeling bodily pain or suffering", "irksome or annoying; requiring effort or exertion"],
 "prediction": ["an act of declaring or indicating in advance; a foretelling on the basis of observation, experience, or scientific reason", "something that is predicted; a forecast"],
 "thereby": ["by that means; because of that", "connected with or with reference to that"],
 "politically": ["in a political manner; with respect to government, politics, or the state"],
 "lung": ["one of the usually paired compound saccular organs that constitute the basic respiratory organ of air-breathing vertebrates"],
 "namely": ["that is to say; to wit"],
 "traditionally": ["in a traditional manner; according to inherited, established, or customary patterns"],
 "inevitably": ["in a way that is incapable of being avoided or evaded; as is certain to happen"],
 "simultaneously": ["at the same time; existing or occurring at the same moment"],
 "strictly": ["in a strict, rigorous, or stringent manner", "with exactness or precision; exclusively or purely"],
 "airplane": ["a powered heavier-than-air aircraft with fixed wings from which it derives most of its lift"],
 "kilometer": ["a metric unit of length equal to 1,000 meters"],
 "effectiveness": ["the power to produce a desired effect or result"],
 "availability": ["the quality or state of being present or ready for immediate use; accessibility"],
 "statistical": ["of, relating to, based on, or employing the principles of statistics — the collection, analysis, and interpretation of numerical data"],
 "punish": ["to impose a penalty on for a fault, offense, or violation", "to deal with roughly or harshly", "to inflict a penalty for the commission of (an offense) in retribution or retaliation"],
 "oxygen": ["a colorless, odorless, tasteless gaseous chemical element that constitutes about 21 percent of the atmosphere and is essential to life"],
 "ridiculous": ["arousing or deserving ridicule; extremely silly or unreasonable; absurd or preposterous"],
 "linguistic": ["of or relating to language or to linguistics, the study of human speech"],
 "separately": ["in a separate manner; apart from others; individually or independently"],
 "importantly": ["in an important manner; significantly — often used to emphasize a point"],
 "bacteria": ["microscopic single-celled organisms that lack a true nucleus and are important because of their chemical effects and disease-causing ability"],
 "sufficiently": ["to a degree or in an amount that is enough to meet the needs of a situation; adequately"],
 "machinery": ["machines in general or as a functioning unit; the working parts of a machine", "the organization or system by which something is done or carried on"],
 "questionnaire": ["a set of questions for obtaining statistically useful or personal information from individuals; a written or printed survey form"],
 "actively": ["in an active manner; with action or participation; energetically"],
 "terribly": ["to an extreme degree; very", "in a manner causing awe, dread, or distress; very badly"],
 "formally": ["in a formal manner: with attention to established form, convention, or ceremony", "in outward appearance or form; officially"],
 "historically": ["in accordance with or with respect to history; in the past"],
 "locally": ["in a particular place or region; within a limited area; not generally or universally"],
 "parental": ["of or relating to a parent or parents; characteristic of or befitting a parent"],
 "invade": ["to enter (a country or territory) for conquest or plunder", "to encroach or intrude upon; to infringe", "to spread over or into as if invading, as a disease through the body"],
 "accurately": ["in a manner free from error; correctly, exactly, or precisely"],
 "positively": ["in a positive manner: with certainty or confidence; favorably or constructively", "used as an intensive to emphasize the truth of a statement"],
 "independently": ["in a manner free from outside control or support; without reliance on others; separately"],
 "individually": ["in an individual manner: personally, singly, or distinctively; one at a time"],
 "broadly": ["in a broad manner: fully or plainly; in a general or wide-ranging way"],
 "electron": ["an elementary particle carrying a single unit of negative electrical charge and found outside the nucleus of an atom"],
 "socially": ["in a social manner; with respect to society or its organization"],
 "calcium": ["a silver-white soft metallic chemical element that is essential to cellular function and is the most abundant mineral in the body, occurring in bones and teeth"],
 "vitamin": ["any of various organic substances that are essential in minute quantities to the nutrition of most animals and some plants and act especially in the regulation of metabolic processes"],
 "explicitly": ["in a manner that is fully revealed or expressed without vagueness or ambiguity; clearly and openly"],
 "credibility": ["the quality or power of inspiring belief; capacity for belief"],
 "rack": ["a framework, stand, or grating on or in which articles are placed", "an instrument of torture on which a body is stretched; a cause of anguish or pain", "to cause to suffer torture, pain, or anguish; to stretch or strain violently"],
 "psychologist": ["a specialist in psychology — the science of mind and behavior; a practitioner who evaluates and treats mental and behavioral conditions"],
 "conceptual": ["of, relating to, or consisting of concepts — abstract or generic ideas; existing in the mind"],
 "overview": ["a general survey or summary"],
 "sustainable": ["capable of being maintained at length without interruption or weakening", "of or relating to a method of harvesting or using a resource so that the resource is not depleted or permanently damaged"],
 "diameter": ["a chord passing through the center of a figure or body, especially of a circle or sphere", "the length of a straight line through the center of an object; thickness"],
 "rejection": ["the act of refusing to accept, consider, or submit to; the state of being refused", "an immune response in which a transplanted organ or tissue is attacked by the recipient's body"],
 "circulate": ["to move in a circle, circuit, or orbit; to flow without obstruction", "to pass from person to person or place to place; to become well known or widespread", "to cause to be distributed or transmitted"],
 "semantic": ["of or relating to meaning in language", "of or relating to semantics — the study of meanings"],
 "simplify": ["to make simple or simpler: to reduce to basic essentials, diminish in scope or complexity, or make more intelligible"],
 "supposedly": ["according to what is generally assumed or believed, often with an implication of doubt"],
 "molecular": ["of, relating to, consisting of, or produced by molecules — the smallest particles of substances that retain their properties"],
 "capitalism": ["an economic system characterized by private or corporate ownership of capital goods, by investments determined by private decision, and by prices, production, and distribution of goods determined mainly by competition in a free market"],
 "minus": ["diminished by; less", "lacking or deprived of (informal)", "a negative quantity; a deficiency or defect"],
 "hydrogen": ["the simplest and lightest chemical element, a colorless, odorless, highly flammable gas that is the most abundant element in the universe"],
 "dioxide": ["an oxide containing two atoms of oxygen in each molecule"],
 "nicely": ["in a pleasing or agreeable manner; well", "with precision, care, or delicacy; exactly"],
 "predominantly": ["for the most part; mainly; in a way that has superior strength, influence, or frequency"],
 "morality": ["a doctrine or system of moral conduct; conformity to ideals of right human conduct", "moral quality or character; virtue", "a literary or other imaginative work teaching a moral lesson"],
 "unintelligible": ["impossible to understand; not able to be comprehended"],
 "antibody": ["any of a large number of proteins produced normally by specialized B cells after stimulation by an antigen that act specifically against the antigen in an immune response"],
 "fundamentally": ["at the most basic level; in essence; with regard to what is essential or of central importance"],
 "sexuality": ["the quality or state of being sexual: the condition of having sex, sexual activity, or expression and receptivity of sexual interest"],
}
MW.update(MW3)
